config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users

  get '/about' => 'about#index'
  get '/contact' => 'contact#index'
  resources   :events
  get '/event/info' => 'events#info'
  resources   :people
  delete 'people/:id/keywords' => 'people#delete_keywords'
  resources   :resources
  delete 'resources/:id/keywords' => 'resources#delete_keywords'
  get '/admin' => 'admin#index'
  resources   :comments
  resources   :users
end

app/views/admin/_add_person.html.erb
<div class="col-lg-12">
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to "Back to Top", "/admin" %>
      </div>
      <%= form_tag(people_path, {:multipart => true}) do %>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <h3>Person Name</h3>
          <input placeholder="名前をカタカナで入力してください" type="text" class="form-control" name="name" autofocus="true"></input>
          <h3>Person Detail</h3>
          <textarea placeholder="Detailを入力してください" name="detail" cols="30" rows="10" class="form-control"></textarea>
          <h3>Person Keywords</h3>
          <input placeholder="キーワード1" type="text" class="form-control" name="keyword1"></input>
          <input placeholder="キーワード2" type="text" class="form-control" name="keyword2"></input>
          <input placeholder="キーワード3" type="text" class="form-control" name="keyword3"></input>
          <input placeholder="キーワード4" type="text" class="form-control" name="keyword4"></input>
          <input placeholder="キーワード5" type="text" class="form-control" name="keyword5"></input>
          <input placeholder="キーワード6" type="text" class="form-control" name="keyword6"></input>
          <input placeholder="キーワード7" type="text" class="form-control" name="keyword7"></input>
          <input placeholder="キーワード8" type="text" class="form-control" name="keyword8"></input>
          <h3>Person Photo</h3>
          <input placeholder="ファイル名を番号で入力してください" type="text" class="form-control" name="pfile"></input>
          <input type="submit" value="送信" class="btn btn-primary withripple">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/_add_resource.html.erb
<div class="col-lg-12">
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to "Back to Top", "/admin" %>
      </div>
      <%= form_tag(resources_path, {:multipart => true}) do %>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <h3>Resource Name</h3>
          <input placeholder="名前をひらがなで入力してください" type="text" class="form-control" name="name" autofocus="true"></input>
          <h3>Resource Detail</h3>
          <textarea placeholder="Detailを入力してください" name="detail" cols="30" rows="10" class="form-control"></textarea>
          <h3>Resource Keywords</h3>
          <input placeholder="キーワード1" type="text" class="form-control" name="keyword1"></input>
          <input placeholder="キーワード2" type="text" class="form-control" name="keyword2"></input>
          <input placeholder="キーワード3" type="text" class="form-control" name="keyword3"></input>
          <input placeholder="キーワード4" type="text" class="form-control" name="keyword4"></input>
          <input placeholder="キーワード5" type="text" class="form-control" name="keyword5"></input>
          <input placeholder="キーワード6" type="text" class="form-control" name="keyword6"></input>
          <input placeholder="キーワード7" type="text" class="form-control" name="keyword7"></input>
          <input placeholder="キーワード8" type="text" class="form-control" name="keyword8"></input>
          <h3>Person Photo</h3>
          <input placeholder="ファイル名を番号で入力してください" type="text" class="form-control" name="pfile"></input>
          <input type="submit" value="送信" class="btn btn-primary withripple">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/_delete_person.html.erb
<div class="col-lg-12">
  <div class="row form">
    <% @people.each do |person| %>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <%= image_tag(person_photo(person), :class => "img-responsive") %>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <h3><%= person.name %></h3>
        <h4>keywords</h4>
        <% person.keywords.each do |keyword| %>
          <p>◆ <%= keyword.name %></p>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to "削除", person_path(person), method: :delete, :class => "btn btn-info normal" %>
      </div>
    <% end %>
    <%= paginate(@people) %>
  </div>
</div>

app/views/admin/_delete_resource.html.erb
<div class="col-lg-12">
  <div class="row form">
    <% @resources.each do |resource| %>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <%= image_tag(resource_photo(resource), :class => "img-responsive") %>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <h3><%= resource.name %></h3>
        <h4>keywords</h4>
        <% resource.keywords.each do |keyword| %>
          <p>◆ <%= keyword.name %></p>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to "削除", resource_path(resource), method: :delete, :class => "btn btn-info normal" %>
      </div>
    <% end %>
    <%= paginate(@resources) %>
  </div>
</div>

app/views/admin/_edit_person.html.erb
<div class="col-lg-12">
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= link_to "Back to Top", "/admin" %>
    </div>
    <% @people.each do |person| %>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <%= image_tag(person_photo(person), :class => "img-responsive") %>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <h3><%= person.name %></h3>
        <h4>keywords</h4>
        <% person.keywords.each do |keyword| %>
          <p>◆ <%= keyword.name %></p>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <br>
        <p><%= br(person.detail) %></p>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to "編集", edit_person_path(person), :class => "btn btn-info normal" %>
      </div>
    <% end %>
    <%= paginate(@people) %>
  </div>
</div>

app/views/admin/_edit_resource.html.erb
<div class="col-lg-12">
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= link_to "Back to Top", "/admin" %>
    </div>
    <% @resources.each do |resource| %>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <%= image_tag(resource_photo(resource), :class => "img-responsive") %>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6">
        <h3><%= resource.name %></h3>
        <h4>keywords</h4>
        <% resource.keywords.each do |keyword| %>
          <p>◆ <%= keyword.name %></p>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <br>
        <p><%= br(resource.detail) %></p>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to "編集", edit_resource_path(resource), :class => "btn btn-info normal" %>
      </div>
    <% end %>
    <%= paginate(@resources) %>
  </div>
</div>

app/views/admin/_general.html.erb
<div class="col-lg-12">
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <p><%= link_to "Add Person", "/admin?command=add_person" %></p>
      <p><%= link_to "Add Resource", "/admin?command=add_resource" %></p>
      <p><%= link_to "Edit Person", "/admin?command=edit_person" %></p>
      <p><%= link_to "Edit Resource", "/admin?command=edit_resource" %></p>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<% if params[:command] == "add_person" %>
  <%= render partial: 'admin/add_person' %>
<% elsif params[:command] == "add_resource" %>
  <%= render partial: 'admin/add_resource' %>
<% elsif params[:command] == "edit_person" %>
  <%= render partial: 'admin/edit_person' %>
<% elsif params[:command] == "edit_resource" %>
  <%= render partial: 'admin/edit_resource' %>
<% else %>
  <%= render partial: 'admin/general' %>
<% end %>