config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users

  get '/about' => 'about#index'
  get '/contact' => 'contact#index'
  resources   :events
  get '/event/info' => 'events#info'
  resources   :people
  delete 'people/:id/keywords' => 'people#delete_keywords'
  resources   :resources
  delete 'resources/:id/keywords' => 'resources#delete_keywords'
  get '/admin' => 'admin#index'
  resources   :comments
  resources   :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  # association
  belongs_to :person
  belongs_to :resource
  belongs_to :user
  has_many :comments, dependent: :destroy

  # scope
  scope :recent, -> { order('created_at DESC') }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :redirect_to_sign_up, only: :new

  def index
    @events = Event.recent.page(params[:page]).per(10)
  end

  def new
    @people = Person.recent.page(params[:page]).per(10)
    @resources = Resource.recent.page(params[:page]).per(10)
    @person = Person.find(new_params[:person_id]) if new_params[:person_id]
    @resource = Resource.find(new_params[:resource_id]) if new_params[:resource_id]
  end

  def create
    if params_complete?
      Event.create(create_params)
    else
      redirect_to new_event_path(person_id: create_params[:person_id], resource_id: create_params[:resource_id])
    end
  end

  def show
    @event = Event.find(id_params[:id])
    @comments = @event.comments.page(params[:page]).per(10)
  end

  def edit
    @event = Event.find(id_params[:id])
  end

  def update
    event = Event.find(id_params[:id])
    event.update(update_params)
  end

  def destroy
    event = Event.find_by(id_params)
    event.destroy if event.user_id == current_user.id
  end

  def info
  end

  private
  def new_params
    params.permit(:person_id, :resource_id)
  end

  def create_params
    params.permit(:detail, :person_id, :resource_id).merge(user_id: current_user.id, name: event_name)
  end

  def name_params
    params.permit(:kata, :hira)
  end

  def id_params
    params.permit(:id)
  end

  def update_params
    params.permit(:name, :detail)
  end

  def params_complete?
    name_params[:kata].present? && name_params[:hira].present? && create_params[:detail].present?
  end

  def event_name
    "#{name_params[:kata]}風#{name_params[:hira]}"
  end

  def redirect_to_sign_up
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/views/events/_event.html.erb
<div class="row form">
  <div class="col-xs-12 col-sm-12 col-md-12 center">
    <h2><%= event.name %> 
      <% if current_user && current_user.id == event.user_id %>
        <small><%= link_to "編集", edit_event_path(event) %>・<%= link_to "削除", event_path(event), method: :delete %></small>
      <% end %>
    </h2>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag(person_photo(event.person), :class => "img-responsive") %>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag("x.png", :class => "img-responsive") %>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag(resource_photo(event.resource), :class => "img-responsive") %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 text_long">
    <h4><%= br(event.detail) %></h4>
    <div class="right">
      <%= link_to event_path(event) do %>
        <p>→イベント詳細</p>
      <% end %>
    </div>
  </div>
</div>

app/views/events/create.html.erb
<div class="col-lg-12">
  <div class="center">
      <%= image_tag("step4.png", :class => "img-responsive") %>
  </div>
  <div class="row form center">
    <h3>イベントが作成されました</h3>
    <%= link_to "イベント一覧へ", events_path, :class => "btn btn-primary withripple" %>
  </div>
</div>

app/views/events/destroy.html.erb
<div class="row form">
  <div class="col-lg-12">
    <div class="center">
      <h3>イベントが削除されました</h3>
      <%= link_to "イベント一覧へ", events_path, :class => "btn btn-primary withripple" %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="row form">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <%= link_to events_path do %>
      <p>一覧に戻る</p>
    <% end %>
  </div>
  <div class="col-xs-5 col-sm-5 col-md-5">
    <%= image_tag(person_photo(@event.person), :class => "img-responsive") %>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag("x.png", :class => "img-responsive") %>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag(resource_photo(@event.resource), :class => "img-responsive") %>
  </div>
</div>
<div class="row form">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <%= form_tag(event_path, method: :patch) do %>
      <h2>イベント名</h2>
      <input placeholder="イベント名を入力してください" type="text" class="form-control" name="name" value="<%= @event.name %>"></input>
      <h2>イベント概要</h2>
      <textarea placeholder="イベント概要を入力してください" name="detail" cols="30" rows="10" class="form-control"><%= @event.detail %></textarea>
      <input type="submit" value="更新する" class="btn btn-primary withripple">
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row form">
  <div class="col-xs-12 col-sm-12 col-md-12 center">
    <h1>イベント一覧</h1>
  </div>
</div>
<%= render @events %>
<%= paginate(@events) %>

app/views/events/info.html.erb
<div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
  <%= image_tag("rule.png", :class => "img-responsive") %>
</div>
<div class="col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
<%= link_to "/events/new" do %>
    <%= image_tag("button.png", :class => "img-responsive") %>
  <% end %>
</div>

app/views/events/new.html.erb
<% if @resource && @person %>
  <%= render partial: 'steps/three' %>
<% elsif @person %>
  <%= render partial: 'steps/two' %>
<% else %>
  <%= render partial: 'steps/one' %>
<% end %>

app/views/events/show.html.erb
<div class="row form">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <%= link_to events_path do %>
      <p>一覧に戻る</p>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 center">
    <h2><%= @event.name %> 
      <% if current_user && current_user.id == @event.user_id %>
        <small><%= link_to "編集", edit_event_path(@event) %>・<%= link_to "削除", event_path(@event), method: :delete %></small>
      <% end %>
    </h2>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag(person_photo(@event.person), :class => "img-responsive") %>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag("x.png", :class => "img-responsive") %>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4">
    <%= image_tag(resource_photo(@event.resource), :class => "img-responsive") %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <h4><%= br(@event.detail) %></h4>
  </div>
  <% if @comments.present? %>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <h2>コメント一覧</h2>
      <% @comments.each do |comment| %>
        <div class="sct_inner">
          <p><%= comment.text %></p>
        </div>
      <% end %>
      <%= paginate(@comments) %>
    </div>
  <% end %>
  <%= form_tag(comments_path) do %>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <h2>コメント投稿</h2>
      <input placeholder="コメントを入力してください" type="text" class="form-control" name="text" autofocus="true"></input>
      <input type="hidden" name="event_id" value="<%= @event.id %>">
    </div>
  <% end %>
</div>

app/views/events/update.html.erb
<div class="row form">
  <div class="col-lg-12 center">
    <h3>イベント内容を更新しました</h3>
    <%= link_to "イベント一覧へ", events_path, :class => "btn btn-primary withripple" %>
  </div>
</div>