config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users

  get '/about' => 'about#index'
  get '/contact' => 'contact#index'
  resources   :events
  get '/event/info' => 'events#info'
  resources   :people
  delete 'people/:id/keywords' => 'people#delete_keywords'
  resources   :resources
  delete 'resources/:id/keywords' => 'resources#delete_keywords'
  get '/admin' => 'admin#index'
  resources   :comments
  resources   :users
end

app/views/resources/_resource.html.erb
<div class="row form">
  <div class="col-xs-6 col-sm-6 col-md-6">
    <%= image_tag(resource_photo(resource), :class => "img-responsive") %>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-6">
    <h3><%= resource.name %></h3>
    <h4>keywords</h4>
    <% resource.keywords.each do |keyword| %>
      <p>◆ <%= keyword.name %></p>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <br>
    <p><%= br(resource.detail) %></p>
  </div>
</div>

app/views/resources/edit.html.erb
<div class="col-lg-12">
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <%= form_tag(resource_path, {:multipart => true, method: :patch}) do %>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <h3>Edit Name</h3>
          <input placeholder="名前をひらがなで入力してください" type="text" class="form-control" name="name" autofocus="true" value="<%= @resource.name %>"></input>
          <h3>Edit Detail</h3>
          <textarea placeholder="Detailを入力してください" name="detail" cols="30" rows="10" class="form-control"><%= @resource.detail %></textarea>
          <h3>Add Keywords</h3>
          <input placeholder="キーワード1" type="text" class="form-control" name="keyword1"></input>
          <input placeholder="キーワード2" type="text" class="form-control" name="keyword2"></input>
          <input placeholder="キーワード3" type="text" class="form-control" name="keyword3"></input>
          <h3>Edit Photo</h3>
          <input placeholder="ファイル名を番号で入力してください" type="text" class="form-control" name="pfile" value="<%= @resource.pfile %>"></input>
          <input type="submit" value="更新" class="btn btn-primary withripple">
        </div>
      <% end %>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <h3>Delete Keywords</h3>
        <%= link_to "削除", "/resources/#{@resource.id}/keywords", :class => "btn btn-primary withripple", method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<div class="col-lg-12">
  <br>
  <div class="row form">
    <div class="col-xs-12 col-sm-12 col-md-12 center">
    <h2>ひらがな一覧</h2>
    </div>
  </div>
  <%= render @resources %>
  <%= paginate(@resources) %>
</div>

app/views/resources/show.html.erb
<div class="row form">
  <div class="col-xs-6 col-sm-6 col-md-6">
    <%= image_tag(resource_photo(@resource), :class => "img-responsive") %>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-6">
    <h3><%= @resource.name %></h3>
    <h4>keywords</h4>
    <% @resource.keywords.each do |keyword| %>
      <p>◆ <%= keyword.name %></p>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <br>
    <p><%= br(@resource.detail) %></p>
    <%= link_to "このひらがなを選択", new_event_path(resource_id: @resource.id, person_id: params[:person_id]), :class => "btn btn-info normal" %>
  </div>
</div>